import './globals.css'
import './styles/bootstrap.css'
import './styles/w3.css'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import { REM } from 'next/font/google'

//components
import Navbar from './components/Navbar'

const rem = REM({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rem.className}>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
