import './globals.css'
import './styles/bootstrap.css'
import './styles/w3.css'
import { REM } from 'next/font/google'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

//components
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const rem = REM({ subsets: ['latin'] })

export const metadata = {
  title: 'Fall Streak',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rem.className}>   
        <Navbar />
        {children}
        <Footer />
      </body>
      
    </html>
  )
}
